using System;
using System.Collections.Generic;
using Shinzui.Application.DTOs.ItemSpawn;
using Shinzui.Application.Interfaces.ItemSpawn;
using Shinzui.Application.Interfaces.ResourceNeed;
using Shinzui.Application.UseCases.ItemSpawn;
using Shinzui.View.ItemSpawn;
using UnityEngine;
using VContainer;

namespace Shinzui.Presentation.ItemSpawn
{
    /// <summary>
    /// アイテムスポーン実行の管理MonoBehaviour。
    /// Application層（DTO/UseCase）およびView層のみに依存し、Clean Architectureに厳格に従う。
    /// Inspector上のコンテキストメニューやAPIからの生成・再生成・クリア、およびVContainerによるDI注入に対応する。
    /// </summary>
    [DisallowMultipleComponent]
    [DefaultExecutionOrder(10)]
    public class ItemSpawnManager : MonoBehaviour
    {
        [Header("Configuration (Application DTO)")]
        [SerializeField] private ItemSpawnConfigDto spawnConfig;
        [SerializeField] private List<ItemSpawnTargetDto> itemTargets = new();
        [SerializeField] private List<GameObject> itemPrefabs = new();

        [Header("Scene References")]
        [SerializeField] private ItemSpawnContainerView containerView;
        [SerializeField] private Transform playerTransform;

        [Header("Runtime Options")]
        [SerializeField] private bool generateOnStart = false;

        private IItemSpawnUseCase _injectedUseCase;
        private INeedWeightProvider _injectedNeedWeightProvider;
        private IExternalPlacementValidator _injectedExternalValidator;
        private ItemSpawnPresenter _presenter;
        private Dictionary<string, GameObject> _prefabMap = new(StringComparer.OrdinalIgnoreCase);
        private int _lastUsedSeed;
        private bool _isStarted;
        private bool _hasMapReadyPendingGenerate;
        private bool _hasAutoGenerated;

        public ItemSpawnResultDto LastRunResult => _presenter?.LastRunResult;
        public int LastUsedSeed => _lastUsedSeed;
        public ItemSpawnConfigDto SpawnConfig => spawnConfig;
        public IReadOnlyList<ItemSpawnTargetDto> ItemTargets => itemTargets;

        [Inject]
        public void Construct(
            IItemSpawnUseCase useCase = null,
            INeedWeightProvider needWeightProvider = null,
            IExternalPlacementValidator externalValidator = null)
        {
            _injectedUseCase = useCase;
            _injectedNeedWeightProvider = needWeightProvider;
            _injectedExternalValidator = externalValidator;
            InitializePresenter();
        }

        public void Configure(
            ItemSpawnConfigDto configDto,
            IReadOnlyList<ItemSpawnTargetDto> targetsDto,
            IReadOnlyDictionary<string, GameObject> prefabMap = null)
        {
            spawnConfig = configDto;
            itemTargets = targetsDto != null ? new List<ItemSpawnTargetDto>(targetsDto) : new List<ItemSpawnTargetDto>();

            _prefabMap.Clear();
            if (prefabMap != null)
            {
                foreach (var kvp in prefabMap)
                {
                    _prefabMap[kvp.Key] = kvp.Value;
                }
            }
            else
            {
                RebuildPrefabMapFromList();
            }

            InitializePresenter();

            // マップ準備完了要求が先行して届いており、まだ自動生成されていない場合はここで実行
            if (_isStarted && _hasMapReadyPendingGenerate && !_hasAutoGenerated && itemTargets.Count > 0)
            {
                _hasMapReadyPendingGenerate = false;
                _hasAutoGenerated = true;
                Generate();
            }
        }

        public void SetNeedWeightProvider(INeedWeightProvider provider)
        {
            _injectedNeedWeightProvider = provider;
            InitializePresenter();
        }

        public void SetExternalValidator(IExternalPlacementValidator validator)
        {
            _injectedExternalValidator = validator;
            InitializePresenter();
        }

        /// <summary>
        /// マップ生成完了通知を受け取り、DI設定およびStart完了のタイミングに合わせて厳密に1回だけアイテム生成を実行する。
        /// </summary>
        public void RequestGenerateAfterMapReady()
        {
            if (_hasAutoGenerated)
            {
                return; // 既に自動生成済みなら重複実行しない
            }

            _hasMapReadyPendingGenerate = true;

            // 既にStart()が実行され、かつターゲットが設定済みの場合は即時生成
            if (_isStarted && itemTargets != null && itemTargets.Count > 0)
            {
                _hasMapReadyPendingGenerate = false;
                _hasAutoGenerated = true;
                Generate();
            }
        }

        private void Awake()
        {
            RebuildPrefabMapFromList();
            if (_presenter == null)
            {
                InitializePresenter();
            }
        }

        private void Start()
        {
            _isStarted = true;

            if (_hasMapReadyPendingGenerate && !_hasAutoGenerated && itemTargets != null && itemTargets.Count > 0)
            {
                _hasMapReadyPendingGenerate = false;
                _hasAutoGenerated = true;
                Generate();
            }
            else if (generateOnStart && !_hasAutoGenerated)
            {
                _hasAutoGenerated = true;
                Generate();
            }
        }

        private void RebuildPrefabMapFromList()
        {
            if (itemTargets == null || itemPrefabs == null) return;

            int count = Math.Min(itemTargets.Count, itemPrefabs.Count);
            for (int i = 0; i < count; i++)
            {
                if (itemTargets[i] != null && !string.IsNullOrEmpty(itemTargets[i].Id) && itemPrefabs[i] != null)
                {
                    _prefabMap[itemTargets[i].Id] = itemPrefabs[i];
                }
            }
        }

        private void InitializePresenter()
        {
            if (containerView == null)
            {
                containerView = GetComponent<ItemSpawnContainerView>();
                if (containerView == null)
                {
                    containerView = FindFirstObjectByType<ItemSpawnContainerView>();
                }
            }

            IItemSpawnUseCase useCase = _injectedUseCase ?? new ItemSpawnUseCase();
            _presenter = new ItemSpawnPresenter(useCase, containerView, _injectedNeedWeightProvider, _injectedExternalValidator);
        }

        /// <summary>
        /// 指定されたシード値でアイテムスポーンを実行する。
        /// </summary>
        public ItemSpawnResultDto Generate(int seed)
        {
            if (_presenter == null)
            {
                InitializePresenter();
            }

            _lastUsedSeed = seed;
            var config = spawnConfig ?? new ItemSpawnConfigDto();
            config.Seed = seed;

            if (playerTransform != null)
            {
                config.PlayerStartX = playerTransform.position.x;
                config.PlayerStartY = playerTransform.position.y;
                config.PlayerStartZ = playerTransform.position.z;
            }

            if (_prefabMap.Count == 0)
            {
                RebuildPrefabMapFromList();
            }

            ItemSpawnResultDto result = _presenter.ExecuteSpawn(config, itemTargets, _prefabMap);
            if (result != null)
            {
                Debug.Log($"[ItemSpawnManager] Spawn completed (Seed: {seed}). Generated {result.TotalSpawnedCount} items. Cost: {result.TotalCostSpent}, Remaining Budget: {result.RemainingBudget}, Failures: {result.FailedPlacementAttempts}.");
            }
            return result;
        }

        /// <summary>
        /// 現在の設定シード値で生成を実行する。
        /// </summary>
        [ContextMenu("Generate (Current Seed)")]
        public void Generate()
        {
            int seed = spawnConfig != null ? spawnConfig.Seed : 2777;
            Generate(seed);
        }

        /// <summary>
        /// 直前と同じシード値で再生成する。
        /// </summary>
        [ContextMenu("Regenerate Same Seed")]
        public void RegenerateSameSeed()
        {
            int seed = _lastUsedSeed != 0 ? _lastUsedSeed : (spawnConfig != null ? spawnConfig.Seed : 2777);
            Generate(seed);
        }

        /// <summary>
        /// 新しいランダムシード値を決定して再生成する。
        /// </summary>
        [ContextMenu("Regenerate New Seed")]
        public void RegenerateNewSeed()
        {
            int newSeed = unchecked(Environment.TickCount * 31 + (int)DateTime.UtcNow.Ticks);
            Generate(newSeed);
        }

        /// <summary>
        /// 生成済みアイテムをすべてクリアする。
        /// </summary>
        [ContextMenu("Clear Generated")]
        public void ClearGenerated()
        {
            if (_presenter != null)
            {
                _presenter.ClearSpawned();
            }
            else if (containerView != null)
            {
                containerView.ClearAllSpawned();
            }
            Debug.Log("[ItemSpawnManager] Cleared all spawned items.");
        }
    }
}
